#
#  MCEEW configuration
#  Last updated on 2.2.1
#
#  API Source: https://api.wolfx.jp
#  Plugin Page: https://acg.kr/mceew
#  Github: https://github.com/TenkyuChimata/MCEEW
#
# ####

########################
# %flag% 予報 or 警報
# %report_time% EEW report time
# %origin_time% Time of Earthquake
# %num% Number of EEW reports
# %lat% Latitude of the epicenter
# %lon% Longitude of the epicenter
# %region% Name of the epicenter
# %mag% Magnitude of earthquake
# %depth% Depth of earthquake
# %shindo% Intensity of earthquake
# %type% 仮定震源 or 最終報 or 訓練 or 仮定震源 (最終報) or 訓練 (最終報) or 取消
# %info% Tsunami information
# \n Change to next line
########################

# Enable Japan JMA EEW broadcast
enable_jp: true

# Enable Sichuan EEW broadcast
enable_sc: true

# Enable Taiwan CWB EEW broadcast
enable_cwb: true

# Set the time format
time_format: "yyyy年MM月dd日 HH時mm分ss秒"
time_format_final: "yyyy年MM月dd日 HH時mm分"

Action:
  # Broadcast messages to chat
  broadcast: true
  # Broadcast messages to title
  title: true
  # Enable sound alert
  alert: true
  # Enable Japan final report broadcast
  final: true
  # Broadcast debug message to console
  debug: false

Message:
  # Set the Japan EEW alert report message format
  Alert:
    # Set the chat message format
    broadcast: "&c緊急地震速報 (%flag%) | 第%num%報 %type%\n &e%origin_time% &f発生\n &f震央: &e%region% (北緯: &e%lat%度 東経: &e%lon%度)\n &fマグニチュード: &e%mag%\n &f深さ: &e%depth%\n &f最大震度: &e%shindo%\n &f更新時間: &e%report_time%"
    # Set the title message format
    title: "&c緊急地震速報 (%flag%)"
    # Set the subtitle message format
    subtitle: "&e%region%で震度%shindo%&eの地震"
  # Set the Japan EEW forecast report message format
  Forecast:
    broadcast: "&e緊急地震速報 (%flag%) | 第%num%報 %type%\n &e%origin_time% &f発生\n &f震央: &e%region% (北緯: &e%lat%度 東経: &e%lon%度)\n &fマグニチュード: &e%mag%\n &f深さ: &e%depth%\n &f最大震度: &e%shindo%\n &f更新時間: &e%report_time%"
    title: "&e緊急地震速報 (%flag%)"
    subtitle: "&e%region%で震度%shindo%&eの地震"
  # Set the Japan final report message format
  Final:
    broadcast: "&e地震情報\n &e%origin_time% &f発生\n &f震央: &e%region%\n &fマグニチュード: &e%mag%\n &f深さ: &e%depth%\n &f最大震度: &e%shindo%\n &f津波情報: &e%info%"
  # Set the Sichuan EEW message format
  Sichuan:
    broadcast: "&c四川地震预警 | 第%num%报\n &e%origin_time% &f发生\n &f震中: &e%region% (北纬: &e%lat%度 东经: &e%lon%度)\n &f震级: &e%mag%\n &f深度: &e%depth%\n &f最大烈度: &e%shindo%\n &f更新时间: &e%report_time%"
    title: "&c四川地震预警"
    subtitle: "&e%region%发生烈度%shindo%&e的地震"
  # Set the Taiwan EEW message format
  Taiwan:
    broadcast: "&c台灣地震預警 | 第%num%報\n &e%origin_time% &f發生\n &f震央: &e%region% (北緯: &e%lat%度 東經: &e%lon%度)\n &f規模: &e%mag%\n &f深度: &e%depth%\n &f更新時間: &e%report_time%"
    title: "&c台灣地震預警"
    subtitle: "&e%region%发生芮氏規模%mag%地震"

Sound:
  # Set the Japan EEW alert report alert
  Alert:
    # Set the alert sound type
    type: "BLOCK_NOTE_BLOCK_PLING"
    # Set the alert sound volume
    volume: 1000.0
    # Set the alert sound pitch
    pitch: 1.0
  # Set the Japan EEW forecast report alert
  Forecast:
    type: "BLOCK_NOTE_BLOCK_PLING"
    volume: 1000.0
    pitch: 1.0
  # Set the Sichuan EEW alert
  Sichuan:
    type: "BLOCK_NOTE_BLOCK_PLING"
    volume: 1000.0
    pitch: 1.0
  # Set the Taiwan EEW alert
  Taiwan:
    type: "BLOCK_NOTE_BLOCK_PLING"
    volume: 1000.0
    pitch: 1.0

# Do not change this
config-version: 1